import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import Layout from "../components/common/Layout";

const Hero = styled.div`
	height: 90vh;
	display: flex;
	justify-content: center;
	align-items: center;
	background: #fff;
`;

const Heading = styled.h1`
	color: #000;
	font-size: 10rem;
	font-weight: 900;
`;

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout pageTitle="Home">
				<p>teste</p>
			</Layout>
		</>
	);
};

export default Home;
