import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import Layout from "../components/common/Layout";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout pageTitle="Home">
				<p>teste</p>
			</Layout>
		</>
	);
};

export default Home;
